spring:
  application:
    name: school-service

  datasource:
    url: jdbc:mysql://localhost:3306/school-service?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
